### ISSUE TITLE
Fix inconsistencies between About Us UI design and frontend implementation

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#101]
Designer Supervising consistency - @Cleverley1 
Frontend Developer - @Efoxa 
**https://zuri-training.github.io/Pro_Team_41_Chunk-File/Front-end/About-us.html**

**Comment by Cleverley1** [comment]
https://zuri-training.github.io/Pro_Team_41_Chunk-File/Front-end/About-us.html

This issue is completed

**Comment by beverly-m** [comment]
@Efoxa please could you add the following people to the slider. They are currently not there. Thank you

![image](https://user-images.githubusercontent.com/71017261/183577917-4f330f14-c7cc-443a-9b02-f240b5623ada.png)

**Comment by beverly-m** [comment]
The logo in the header is also larger than it is on other screens. @Efoxa kindly reduce the logo to match other screens.

This is how the logo looks in the About Us screen:
![image](https://user-images.githubusercontent.com/71017261/183578437-500413c9-eae6-4469-b64a-a0d5fc4620f2.png)

This is how it looks on other screens:
![image](https://user-images.githubusercontent.com/71017261/183578637-9cd5a754-5cb7-4090-8219-37abbc26fae3.png)

**Comment by Cleverley1** [comment]
@Efoxa Please look into this and close this issue

**Comment by Efoxa** [comment]
inconsistencies corrected. About-us Updated
**https://zuri-training.github.io/Pro_Team_41_Chunk-File/Front-end/About-us.html**
