### ISSUE TITLE
Fix inconsistencies between Documentation page UI design and frontend implementation

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#103]
Designer Supervising consistency - @Cleverley1 
Frontend Developer - @Olabanky

**Comment by Cleverley1** [comment]
Olabanki is not the one working on the documentation page, its Daniel

**Comment by Olabanky** [comment]
Yes...I started it but later sent to him due to low battery on my system.

**Comment by Olabanky** [comment]
Yes...I started it but later sent to him due to low battery on my system.

**Comment by Superfly101** [comment]
Done
