### ISSUE TITLE
Fix inconsistencies between Dashboard (Library page) UI design and frontend implementation

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#106]
Designers Supervising consistency - @Oyetokeanu and @beverly-m 
Frontend Developers - @Superfly101 and @MNderi

**Comment by beverly-m** [comment]
@Superfly101 and @MNderi kindly check the logout button and ensure it is linked to the log-out modal. Thank you.

![image](https://user-images.githubusercontent.com/71017261/183580435-48343444-d901-425d-90d3-c1998bd2d1fd.png)

**Comment by beverly-m** [comment]
@Superfly101 @MNderi the font size of the user's email is 18px and the weight is semibold. Kindly look into this.
![image](https://user-images.githubusercontent.com/71017261/183580859-72c211b0-6112-4837-a2a3-dc64b4f51429.png)

**Comment by beverly-m** [comment]
There is a typo here in the word "chunking" @Superfly101 @MNderi 

![image](https://user-images.githubusercontent.com/71017261/183581033-e231bbc7-311b-4d10-abe4-16d4576b6cef.png)

**Comment by beverly-m** [comment]
@Superfly101 @MNderi The color of this message should be #F3930C, font size 12px and weight semibold. Kindly add the warning icon as well.

![image](https://user-images.githubusercontent.com/71017261/183581923-4c85461e-8059-4dce-bc86-ebebc8e751b5.png)

This is how the design is on Figma:

![image](https://user-images.githubusercontent.com/71017261/183582080-49809902-5836-4f73-82eb-8ae21443685d.png)

**Comment by beverly-m** [comment]
@Superfly101 @MNderi kindly check the navigation drawer. Its size changes when the user navigates to the account settings page.

Navigation drawer when user is on the library page:
![image](https://user-images.githubusercontent.com/71017261/183583060-90e6629d-3c77-4f24-8fc7-4859684eeaf8.png)

Navigation drawer when the user is on the account settings page:
![image](https://user-images.githubusercontent.com/71017261/183583248-6f7ee5ca-7ecc-4e97-9755-684f5af2da61.png)

**Comment by Oyetokeanu** [comment]
Work done.
![Dashboard - Library Page - Chunk file modal - 1 (Options selected)](https://user-images.githubusercontent.com/105270093/183778943-dd82e0a4-4463-460e-8358-a50a7dfe2ac3.png)
![Dashboard Hifi - Library Page - Open navigation drawer (1)](https://user-images.githubusercontent.com/105270093/183779012-bffb2a5c-fcdc-4ec8-b855-d75650461c66.png)
![Dashboard Hifi - Library Page - Open navigation drawer](https://user-images.githubusercontent.com/105270093/183779065-4881d8ce-6712-4238-ab0c-699989659d3f.png)
![Dashboard - Library Page - Closed navigation drawer](https://user-images.githubusercontent.com/105270093/183779236-9a95e7b6-e82c-40b2-a6d3-7a12f85b33ef.png)

I ensure there is consistency on the Library pages.

**Comment by Oyetokeanu** [comment]
work done.
https://zuri-training.github.io/Pro_Team_41_Chunk-File/Front-end/dashboard.html
