### ISSUE TITLE
Making the landing page responsive and achieving a pixel perfect design

### ISSUE THREAD

**Issue by TechFlow247** [zuri-training/Pro_Team_41_Chunk-File#109]
This is to achieve a pixel-perfect design while also making the page responsive

**Comment by beverly-m** [comment]
@TechFlow247 and @Jaay06 there is an issue associated with this already. Kindly check this issue: https://github.com/zuri-training/Pro_Team_41_Chunk-File/issues/100

**Comment by TechFlow247** [comment]
ok
