### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Dammina001** [zuri-training/Pro_Team_41_Chunk-File#115]
comment here and drop your designs for those of us that worked on designing the logo for our platform

**Comment by Dammina001** [comment]
My entry for the Logo design although it wasn't what we ended up using
![20220725_203400_0000.png](https://user-images.githubusercontent.com/105244491/183614312-f3fc92ff-dc8b-460e-ac23-17dc0ab54129.png)

**Comment by Dammina001** [comment]
> My entry for the Logo design although it wasn't what we ended up using
> ![20220725_203400_0000.png](https://user-images.githubusercontent.com/105244491/183614312-f3fc92ff-dc8b-460e-ac23-17dc0ab54129.png)

The other entry
![20220725_202451_0000.png](https://user-images.githubusercontent.com/105244491/183614554-9c32ebe4-a26d-4064-aaf9-001069724814.png)

**Comment by Sanctogiacomo** [comment]
![Group 27](https://user-images.githubusercontent.com/34182509/183654513-1c619c88-5365-455d-aa7b-d40830964023.png)
![Group 28](https://user-images.githubusercontent.com/34182509/183654523-5a41b158-1889-4886-84d3-107aa42cc293.png)
![Frame 27](https://user-images.githubusercontent.com/34182509/183654526-eb63991e-eedf-45cf-9a12-3f39486a8921.png)
![Group 23](https://user-images.githubusercontent.com/34182509/183654534-5c24e27a-2867-4a3b-b009-204235ba0716.png)

**Comment by TechFlow247** [comment]
![Grey](https://user-images.githubusercontent.com/105310620/183788249-a8b9605d-22de-49c9-af7a-4ffbaebf1862.png)
![Black](https://user-images.githubusercontent.com/105310620/183788252-3a36c371-c85c-452c-ade5-c39fd81064b7.png)
