### ISSUE TITLE
Wireframing & Low-fidelity for all desktop screens

### ISSUE THREAD

**Issue by Cleverley1** [zuri-training/Pro_Team_41_Chunk-File#48]
Low-Fidelity design for all desktop screens

**Comment by beverly-m** [comment]
[https://www.figma.com/file/YsY3SLQhwZMthzbW6R1xWb/Project_Chunk_File_team_41?node-id=0%3A1](url)

**Comment by beverly-m** [comment]
[https://www.figma.com/file/YsY3SLQhwZMthzbW6R1xWb/Project_Chunk_File_team_41?node-id=620%3A6](url)

**Comment by Ebuka500** [comment]
@nigho-seth is finalizing that

**Comment by nigho-seth** [comment]
Done

**Comment by nigho-seth** [comment]
Done

**Comment by TechFlow247** [comment]
Am done on my end as well

**Comment by Cleverley1** [comment]
D

**Comment by AugustaOkwor1** [comment]
Done
