### ISSUE TITLE
Designing of high-fidelity screens (Desktop view)

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#56]
Landing page - @TechFlow247 
About Us page - @Cleverley1 
Sign In/ Sign Up pages - @Sanctogiacomo and @Ebuka500 
Documentation pages - @Cleverley1 and @AugustaOkwor1 
Dashboard pages - @beverly-m and @UgoKing

**Comment by Ebuka500** [comment]
@beverly-m this is being worked on, adding some finishing touches to it.
it will be ready before 12noon WAT

**Comment by TechFlow247** [comment]
Task completed, am through with the Hi-Fi designs

**Comment by Sanctogiacomo** [comment]
Done with the HIFI designs

**Comment by AugustaOkwor1** [comment]
Done

**Comment by Cleverley1** [comment]
Done on my end
