### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by Efoxa** [zuri-training/Pro_Team_41_Chunk-File#60]

**Comment by Dammina001** [comment]
I'm on it Team

**Comment by Dammina001** [comment]
> I'm on it Team

I'm done,how do I send it here

**Comment by Efoxa** [comment]
Drop the link to the completed task here._

**Comment by Dammina001** [comment]
[Technical documentation .pdf](https://github.com/zuri-training/Pro_Team_41_Chunk-File/files/9274841/Technical.documentation.pdf)
