### ISSUE TITLE
First Video Presentation

### ISSUE THREAD

**Issue by EstherOyebode** [zuri-training/Pro_Team_41_Chunk-File#76]
We are to work on the video presentation for the first presentation. Create slides and use Zoom for the video.

**Comment by Sanctogiacomo** [comment]
Okay! Have anyone been assigned to the task yet?

**Comment by EstherOyebode** [comment]
Done and submitted successfully

**Comment by EstherOyebode** [comment]
Yes @Sanctogiacomo

**Comment by MetuJane** [comment]
Done
