### ISSUE TITLE
Mobile Responsiveness of Web screens Design

### ISSUE THREAD

**Issue by EstherOyebode** [zuri-training/Pro_Team_41_Chunk-File#77]
We are to create the mobile screens for our web pages. We need to make sure they are responsive.

**Comment by EstherOyebode** [comment]
Sign Up/Sign in/Forgot password screens done successfuly.

**Comment by TechFlow247** [comment]
The landing page has now been converted to a mobile version successfully

**Comment by Daberetech** [comment]
The Modal screens for the upload files, download files, delete files and chunking files, for the mobile screens has been completed.

**Comment by Preshtyrace** [comment]
The Library page for the mobile version has been completed.

**Comment by Oyetokeanu** [comment]
The responsive of the web screens Design Done.

**Comment by Oyetokeanu** [comment]
Completed

**Comment by thejourneybeginsng** [comment]
The contact/FAQ has been completed

**Comment by nigho-seth** [comment]
The account settings profile page has been completed
