### ISSUE TITLE
Ensure consistency across all screens on Figma

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#78]
Buttons & other components - @EstherOyebode 
Typography (Page Title, Headings, Body Text) - @thejourneybeginsng 
Spacing (Padding & Margins) - @beverly-m  
Color - @UgoKing 
Alignment & Text Resizing - @TechFlow247

**Comment by EstherOyebode** [comment]
Buttons, header, and footer were completed successfully. Please confirm.

**Comment by TechFlow247** [comment]
Spacing, alignment and text resizing has now been completed

**Comment by Vixxena** [comment]
Prototyping of;
Dashboard Navigation
Upload screen
Download zipped files 📂 💯 done

**Comment by UgoKing** [comment]
Color is now consistent across all devices.

**Comment by Vixxena** [comment]
Prototyping for Mobile screens now completed.

**Comment by beverly-m** [comment]
Spacing across all screens is now on point.
