### ISSUE TITLE
Prototype Hi-Fi and Mobile Responsive screens

### ISSUE THREAD

**Issue by nigho-seth** [zuri-training/Pro_Team_41_Chunk-File#79]

**Comment by MetuJane** [comment]
On it!

**Comment by Sanctogiacomo** [comment]
Almost done

**Comment by Daberetech** [comment]
On it.

**Comment by Oyetokeanu** [comment]
Done

**Comment by beverly-m** [comment]
Thank you for the great work guys! Im closing this issue since we are done.

**Comment by thejourneybeginsng** [comment]
Done with Contact and FAQ

**Comment by Oyetokeanu** [comment]
Prototype of the Hifi 
![Dashboard Hifi - Library Page-Upload file modal-1](https://user-images.githubusercontent.com/105270093/183786368-97d11b9a-61da-4eb4-b905-18db023db38b.png)

**Comment by Oyetokeanu** [comment]
![Dashboard Hifi - Library Page-Upload file modal-1 (1)](https://user-images.githubusercontent.com/105270093/183786544-04a69d16-fe8b-45d1-b2f3-b69b4879bf49.png)
![Dashboard Hifi - Library Page-Upload file modal-1 (1)](https://user-images.githubusercontent.com/105270093/183787154-e8ed476b-1376-4ebd-8ab5-0f7ee1e3ab22.png)

![Dashboard Hifi - Library Page-All files selected](https://user-images.githubusercontent.com/105270093/183789281-5bae5006-579c-42b8-8b59-ecfba8ab72ab.png)

![Dashboard Hifi - Library Page-With Saved Files](https://user-images.githubusercontent.com/105270093/183787740-b364da41-95dc-4e3d-a9ae-fe9e79b506ad.png)
![Dashboard HIfi - Library Page-Download files modal](https://user-images.githubusercontent.com/105270093/183787911-a57311e0-ecc3-47d1-a016-53cc4274429e.png)

![Dashboard Hifi - Library Page-With Saved Files (1)](https://user-images.githubusercontent.com/105270093/183788068-36853476-c780-4dd1-8a40-3e1ef4b9ee3d.png)

![Dashboard Hifi - Library Page-One file selected](https://user-images.githubusercontent.com/105270093/183788167-24d5b1f3-dd22-4673-a441-eed8d2a5b869.png)
![Dashboard Hifi - Library Page-Delete File Modal](https://user-images.githubusercontent.com/105270093/183788305-85b0a481-54df-478f-8a38-6abfa878ac85.png)

![Dashboard Hifi - Library Page-Error Notification](https://user-images.githubusercontent.com/105270093/183788763-a49ef8a8-cd49-4ed2-a503-67abf718e4a4.png)
![Dashboard Hifi - Library Page-Success Notification (2)](https://user-images.githubusercontent.com/105270093/183789019-d3e3d97d-c3e9-4c11-a083-bd097918d1f4.png)

![Dashboard Hifi - Library Page-All files selected (1)](https://user-images.githubusercontent.com/105270093/183789424-1721f955-264a-4c14-bcbc-1ca724f74be7.png)

![Dashboard Hifi - Library Page-All files selected (1)](https://user-images.githubusercontent.com/105270093/183789561-9b1fcfb0-8e66-4e3b-9756-ee63cb5ead22.png)

Prototyping of the Hifi has been done **from Download Chunked files to Delete Confirmation**
