### ISSUE TITLE
Review all our writings for the documentation page.

### ISSUE THREAD

**Issue by MetuJane** [zuri-training/Pro_Team_41_Chunk-File#83]

**Comment by Vixxena** [comment]
Done

**Comment by MetuJane** [comment]
I’m closing this since we are done.

**Comment by judahson-1** [comment]
Okay

**Comment by Cleverley1** [comment]
You can close it

**Comment by MetuJane** [comment]
Documentation google doc link: https://docs.google.com/document/d/18BAmmkxITchlJAGZkUTknVbiR9jCGYgC/edit?usp=sharing&ouid=102043229206258254836&rtpof=true&sd=true

**Comment by Cleverley1** [comment]
This now done
