### ISSUE TITLE
Updating the documentation page

### ISSUE THREAD

**Issue by Cleverley1** [zuri-training/Pro_Team_41_Chunk-File#89]
Update the contents for the documentation page

**Comment by Cleverley1** [comment]
https://zuri-training.github.io/Pro_Team_41_Chunk-File/

**Comment by beverly-m** [comment]
@Cleverley1 I have included @AugustaOkwor1 as well since you worked together. Confirm you are done with the design of the documentation page? If so, please close the issue.

**Comment by Cleverley1** [comment]
Am Done with it

**Comment by AugustaOkwor1** [comment]
Done
