### ISSUE TITLE
Handing over UI designs and resources (icons, style guide, images etc.) to the developers.

### ISSUE THREAD

**Issue by beverly-m** [zuri-training/Pro_Team_41_Chunk-File#99]
Sign Up page resources - @beverly-m 
Sign In page resources - @Ebuka500 
Landing page resources - @UgoKing 
About Us page resources - @UgoKing 
Dashboard pages resources - @beverly-m

**Comment by beverly-m** [comment]
Drive folder with all the resources: https://drive.google.com/drive/folders/1q5QJV82jU4UFxDu4Ot-MNqXtBDHEx6qn?usp=sharing

**Comment by beverly-m** [comment]
I drafted a document with the design specifications for easier communication with the developers: https://docs.google.com/document/d/1ROzzxKEmtQ8xCY31aFkxIwkSk4_GBbJ387-ro0T7lJE/edit?usp=sharing

**Comment by UgoKing** [comment]
I exported the landing page, the illustrations, icons and images to google drive for easy access  for developers
